version: "3"

tasks:
  create-cluster:
    cmds:
      - k3d cluster create --config k3d-config.yaml

  build-image:
    cmds:
      - docker build -t ttl.sh/sensei/simple-image:24h -f patroni/Dockerfile patroni

  push-image:
    cmds:
      - docker push ttl.sh/sensei/simple-image:24h

  label-workers:
    cmds:
      - kubectl get nodes -o name | grep agent | xargs -P 4 -I {} kubectl label {} node-role.kubernetes.io/agent=

  initial-setup:
    cmds:
      - task: create-cluster
      - task: build-image
      - task: push-image
      - task: label-workers

  apply-terraform:
    cmds:
      - terraform -chdir=terraform apply

  sensei-port-forward:
    cmds:
      - kubectl port-forward -n default services/sensei 5432:5432

  grafana-port-forward:
    cmds:
      - kubectl port-forward -n monitoring services/grafana 3000:80

  noco-port-forward:
    cmds:
      - kubectl port-forward -n default services/nocodb-service 8080:8080

  cleanup:
    cmds:
      - k3d cluster delete patroni-poc
