apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sensei.fullname" . }}
  labels:
    {{- include "sensei.labels" . | nindent 4 }}

type: Opaque
stringData:
  superuser-password: {{ .Values.creds.superuser.password }}
  replication-password: {{ .Values.creds.replication.password }}
