apiVersion: v1
kind: Service
metadata:
  name: {{  include "sensei.fullname" .  }}-config
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
spec:
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensei.fullname" . }}
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "sensei.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensei.fullname" . }}-primary
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
    role: primary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "sensei.selectorLabels" . | nindent 4 }}
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensei.fullname" . }}-monitor
  annotations:
    prometheus.io/port: "metrics"
    prometheus.io/scrape: "true"
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8008
      targetPort: 8008
      name: metrics
  selector:
    {{- include "sensei.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sensei.fullname" . }}-repl
  labels:
    {{- include "sensei.labels" . | nindent 4 }}
    role: replica
spec:
  type: ClusterIP
  selector:
    {{- include "sensei.labels" . | nindent 4 }}
    role: replica
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
---
